"use client";
import { useState } from "react";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Plus,Trash2 } from "lucide-react";
import { localDay } from "@/lib/domain";
import type { Meeting } from "@/lib/types";
export function CreateMeeting({open,onOpenChange,onCreate}:{open:boolean;onOpenChange:(v:boolean)=>void;onCreate:(m:Meeting)=>void}){
 const [people,setPeople]=useState([{name:"",department:""}]);
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="meeting-dialog"><DialogHeader><DialogTitle>Новое совещание</DialogTitle><DialogDescription>Добавьте участников и вопросы повестки.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const agenda=String(f.get("agenda")).split("\n").map(x=>x.trim()).filter(Boolean);if(!agenda.length){const field=e.currentTarget.elements.namedItem("agenda") as HTMLTextAreaElement;field.setCustomValidity("Добавьте хотя бы один вопрос повестки.");field.reportValidity();return;}onCreate({id:crypto.randomUUID(),title:String(f.get("title")).trim(),date:String(f.get("date")),agenda,participants:people.map(p=>({...p,name:p.name.trim(),department:p.department.trim(),id:crypto.randomUUID()})),transcript:[]});}}><label>Название совещания<input name="title" required maxLength={180} pattern=".*\S.*" placeholder="Например, планирование работы отдела" autoFocus/></label><label>Дата и время<input name="date" type="datetime-local" required defaultValue={localDay()+"T10:00"}/></label><div className="form-subhead">Участники</div>{people.map((p,i)=><div className="participant-inputs" key={i}><label><span className="sr-only">Имя участника {i+1}</span><input aria-label={`Имя участника ${i+1}`} required pattern=".*\S.*" placeholder="Имя и фамилия" value={p.name} onChange={e=>setPeople(people.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/></label><label><span className="sr-only">Подразделение участника {i+1}</span><input aria-label={`Подразделение участника ${i+1}`} required pattern=".*\S.*" placeholder="Подразделение" value={p.department} onChange={e=>setPeople(people.map((x,n)=>n===i?{...x,department:e.target.value}:x))}/></label>{people.length>1&&<button type="button" className="icon-button" aria-label={`Удалить участника ${i+1}`} onClick={()=>setPeople(people.filter((_,n)=>n!==i))}><Trash2 size={16}/></button>}</div>)}<button type="button" className="text-link add-person" onClick={()=>setPeople([...people,{name:"",department:""}])}><Plus size={15}/>Добавить участника</button><label>Повестка<textarea name="agenda" onChange={e=>e.currentTarget.setCustomValidity("")} required rows={3} placeholder="Каждый вопрос с новой строки"/></label><div className="form-footer"><button type="button" className="secondary" onClick={()=>onOpenChange(false)}>Отмена</button><button className="primary" type="submit">Создать совещание</button></div></form></DialogContent></Dialog>
}

