import type { AppState, Meeting, Participant, Assignment } from "./types";
import { dateOffset } from "./domain";
const people: Participant[]=[{id:"p1",name:"Анна Смирнова",department:"Администрация"},{id:"p2",name:"Дмитрий Волков",department:"ИТ-департамент"},{id:"p3",name:"Елена Морозова",department:"Финансовый отдел"},{id:"p4",name:"Алексей Козлов",department:"Отдел развития"}];
export function seedState():AppState {
 const titles=["Развитие цифрового документооборота","Планирование работы на IV квартал","Еженедельная встреча команды","Оптимизация внутренних процессов","Бюджет и ресурсы проекта"];
 const agendas=[["Внедрение интеллектуального протоколирования","Подготовка пилотного запуска"],["Приоритеты подразделений","План работ на квартал"],["Результаты недели","Следующие шаги"],["Согласование документов","Сокращение сроков обработки"],["Бюджет пилотного проекта","Распределение ресурсов"]];
 const meetings:Meeting[]=titles.map((title,i)=>({id:`demo-m${i}`,title,date:dateOffset(i===0?0:i===2?1:-i)+"T"+(i===2?"14:30":"10:00"),participants:people,agenda:agendas[i],transcript:[],demo:true}));
 const texts=["Подготовить технические требования к модулю протоколирования","Согласовать план внедрения с руководителями подразделений","Подготовить план работ ИТ-департамента на IV квартал","Оценить бюджет пилотного запуска","Обновить регламент согласования документов","Собрать обратную связь от сотрудников","Утвердить состав рабочей группы","Подготовить расчёт затрат на инфраструктуру"];
 const tasks:Assignment[]=texts.map((text,i)=>{const m=meetings[i<2?0:i<4?1:i<6?3:4];const p=people[1+i%3];return{id:`demo-a${i}`,meetingId:m.id,text,assignee:p.name,department:p.department,deadline:dateOffset([5,7,1,-2,2,5,-3,0][i]),initiator:people[0].name,agenda:m.agenda[i%2],status:i===6?"done":i%2?"new":"progress"}});
 meetings.forEach((m,i)=>{if(i===2)return;m.protocol={themes:m.agenda.join("\n"),decisions:i===0?"Запустить пилотный проект автоматического протоколирования.\nПодготовить требования и согласовать план внедрения.":"Согласовать план действий и закрепить ответственных по вопросам повестки.",assignments:tasks.filter(a=>a.meetingId===m.id),...(i===0?{}:{approvedAt:new Date().toISOString()})};m.transcript=[{id:`t${i}-1`,speaker:people[0].name,time:"00:00",text:`Коллеги, сегодня обсуждаем: ${m.agenda.join(" и ").toLowerCase()}. Необходимо согласовать дальнейшие действия.`},{id:`t${i}-2`,speaker:people[1].name,time:"00:42",text:"Предлагаю начать с подготовки требований и согласования плана работ с подразделениями."},{id:`t${i}-3`,speaker:people[0].name,time:"01:18",text:"Зафиксируем решения в протоколе и назначим ответственных по каждому поручению."}];});
 return {version:1,meetings,assignments:tasks.filter(a=>a.meetingId!=="demo-m0")};
}
export function resetDemo(state:AppState):AppState {const demo=seedState();const ids=new Set(state.meetings.filter(m=>m.demo).map(m=>m.id));return{version:1,meetings:[...state.meetings.filter(m=>!m.demo),...demo.meetings],assignments:[...state.assignments.filter(a=>!ids.has(a.meetingId)),...demo.assignments]};}
