"""initial meeting backend

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("meeting_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "PROCESSING",
                "AWAITING_MAPPING",
                "ANALYZING",
                "COMPLETED",
                "FAILED",
                name="meetingstatus",
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("original_path", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("detected_language", sa.String(length=20), nullable=True),
        sa.Column("processing_time", sa.Float(), nullable=True),
        sa.Column("stt_model", sa.String(length=100), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("decisions", sa.JSON(), nullable=False),
        sa.Column("analysis_stale", sa.Boolean(), nullable=False),
        sa.Column("analysis_version", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    op.create_table(
        "jobs",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Enum("TRANSCRIBE", "ANALYZE", name="jobkind"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCEEDED", "FAILED", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("allow_unmapped", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_jobs_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_meeting_id"), "jobs", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(
        "uq_jobs_active_meeting",
        "jobs",
        ["meeting_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"),
        sqlite_where=sa.text("status IN ('PENDING', 'RUNNING')"),
    )
    op.create_table(
        "participants",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("position", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_participants_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
        sa.UniqueConstraint("meeting_id", "id", name=op.f("uq_participants_meeting_id")),
    )
    op.create_index(
        op.f("ix_participants_meeting_id"), "participants", ["meeting_id"], unique=False
    )
    op.create_table(
        "transcript_segments",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("speaker_id", sa.String(length=64), nullable=False),
        sa.Column("start", sa.Float(), nullable=False),
        sa.Column("end", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            'start >= 0 AND "end" > start', name=op.f("ck_transcript_segments_valid_interval")
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_transcript_segments_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
        sa.UniqueConstraint(
            "meeting_id", "ordinal", name=op.f("uq_transcript_segments_meeting_id")
        ),
    )
    op.create_index(
        op.f("ix_transcript_segments_meeting_id"),
        "transcript_segments",
        ["meeting_id"],
        unique=False,
    )
    op.create_table(
        "speakers",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("speaker_id", sa.String(length=64), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id", "participant_id"],
            ["participants.meeting_id", "participants.id"],
            name=op.f("fk_speakers_meeting_id_participants"),
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_speakers_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speakers")),
        sa.UniqueConstraint("meeting_id", "speaker_id", name=op.f("uq_speakers_meeting_id")),
    )
    op.create_index(op.f("ix_speakers_meeting_id"), "speakers", ["meeting_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("responsible_participant_id", sa.Uuid(), nullable=True),
        sa.Column("responsible_name", sa.Text(), nullable=True),
        sa.Column("responsible_speaker_id", sa.String(length=64), nullable=True),
        sa.Column("assigned_by", sa.Text(), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_raw", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NEW", "IN_PROGRESS", "COMPLETED", "OVERDUE", "CANCELLED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("low", "normal", "high", "urgent", name="priority"), nullable=False
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_transcript_start", sa.Float(), nullable=True),
        sa.Column("source_transcript_end", sa.Float(), nullable=True),
        sa.Column("source_quote", sa.Text(), nullable=False),
        sa.Column("extraction_key", sa.String(length=64), nullable=False),
        sa.Column("analysis_version", sa.Integer(), nullable=False),
        sa.Column("edited_by_user", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_tasks_valid_confidence")
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id", "responsible_participant_id"],
            ["participants.meeting_id", "participants.id"],
            name=op.f("fk_tasks_meeting_id_participants"),
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_tasks_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("meeting_id", "extraction_key", name=op.f("uq_tasks_meeting_id")),
    )
    op.create_index(op.f("ix_tasks_deadline"), "tasks", ["deadline"], unique=False)
    op.create_index(op.f("ix_tasks_meeting_id"), "tasks", ["meeting_id"], unique=False)
    op.create_index(
        op.f("ix_tasks_responsible_participant_id"),
        "tasks",
        ["responsible_participant_id"],
        unique=False,
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_responsible_participant_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_meeting_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_deadline"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_speakers_meeting_id"), table_name="speakers")
    op.drop_table("speakers")
    op.drop_index(op.f("ix_transcript_segments_meeting_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index(op.f("ix_participants_meeting_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_index(
        "uq_jobs_active_meeting",
        table_name="jobs",
        postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"),
        sqlite_where=sa.text("status IN ('PENDING', 'RUNNING')"),
    )
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_meeting_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("meetings")
    if op.get_bind().dialect.name == "postgresql":
        for name in ("priority", "taskstatus", "jobstatus", "jobkind", "meetingstatus"):
            sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
